### ISSUE TITLE
add Ubuntu dependencies to avoid "Chrome failed to launch" from CI

### ISSUE THREAD

**Issue by theDavidBarton** [theDavidBarton/puppeteer-daily-menu-scraper#317]
#314 

https://github.com/puppeteer/puppeteer/blob/7176aad32f4bae070003f26645fd097f61c4e47f/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by theDavidBarton** [comment]
add something like this to the workflows yml:

I.)
⭐ ⭐ 
```
# libgbm-dev is required by Puppeteer 3+
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libgbm-dev
```
source: https://github.com/asciidoctor/asciidoctor.js/blob/6d460ffc31362351feca5fdff586f43ed2cab43b/.github/workflows/build-upstream.yml

---
II.)
⭐ ⭐ ⭐ 
```
# libgbm-dev is required by Puppeteer 3+
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libgbm-dev
      if: ${{ runner.os == 'Linux' }}
```
source: https://github.com/Mogztter/asciidoctor-kroki/blob/310f368541fee6c9ee504bba318dc445276e9bc3/.github/workflows/build.yml
---
III.)
⭐ ⭐ ⭐ ⭐ ⭐ 
```
build:
    runs-on: ubuntu-latest
    steps:
    - name: Install puppeteer libraries
      run: sudo apt-get update; sudo apt-get install -y libgbm-dev
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
```
source: https://github.com/CurationCorp/react-use-infinite-loader/blob/2a8e73cdc4f5aa11f5be8f800459ecdbfdfb7f17/.github/workflows/test.yml
